// this file was generated by @mercateo/ws - do not modify it manually
const IntlMessageFormat = require('intl-messageformat');
const INTL_LOCALE = process.env.INTL_LOCALE;

const cachedMessages: { [s: string]: any } = {};

