// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/typed-resolve-from/183ecbeca1b93aef8e57c8faffcf1f145303b82a/index.d.ts
declare module '~resolve-from/index' {
function resolveFrom(fromDir: string, moduleId: string): string;

export = resolveFrom;
}
declare module 'resolve-from/index' {
import alias = require('~resolve-from/index');
export = alias;
}
declare module 'resolve-from' {
import alias = require('~resolve-from/index');
export = alias;
}
